#need to move dev here when production exit
#Need to target this docker files on Docker build
#docker build -f Dockerfile.dev



#Docker file for production
#FROM node:16-alpine as builder
#WORKDIR '/client'
#COPY  package.json .
# RUN npm install
#COPY . .
#RUN npm run build

#FROM nginx
#COPY --from=builder /app/build /usr/share/nginx/html