FROM node:16-buster

MAINTAINER Eastern Lai <eastern.lai@gmail.com>

WORKDIR /client-service

COPY package.json /client-service/package.json

RUN npm install

COPY . /client-service

EXPOSE 3000

CMD ["npm", "start"]


#need to move dev here when production exit
#Need to target this docker files on Docker build
#docker build -f Dockerfile.dev



#Docker file for production
#FROM node:16-alpine as builder
#WORKDIR '/client'
#COPY  package.json .
# RUN npm install
#COPY . .
#RUN npm run build

#FROM nginx
#COPY --from=builder /app/build /usr/share/nginx/html