export const announcementTypes = {

    GET_ANNOUNCEMENTS_START: 'GET_ANNOUNCEMENTS_START',
    GET_ANNOUNCEMENTS_SUCCESS: 'GET_ANNOUNCEMENTS_SUCCESS',
    ADD_ANNOUNCEMENT_START: 'ADD_ANNOUNCEMENT_START',
    ADD_ANNOUNCEMENT_SUCCESS: 'ADD_ANNOUNCEMENT_SUCCESS',
    DELETE_ANNOUNCEMENT : 'DELETE_ANNOUNCEMENT',
    CREATE_ANNOUNCEMENT: 'CREATE_ANNOUNCEMENT',
}

export default announcementTypes;